// integrations/vue/test-app/src/examples/ModusDateExamples.vue
<template>
  <div>
    <h3>Modus Date</h3>
    <ModusWcDate
      aria-label="Date input"
      :bordered="true"
      :disabled="false"
      label="Label"
      :readOnly="false"
      :required="false"
      size="md"
      value=""
    />
  </div>
</template>

<script setup lang="ts">
import { ModusWcDate } from '@trimble-oss/moduswebcomponents-vue';
</script>

// integrations/react/test-react-v19/src/examples/ModusDateExamples.tsx
import { useState } from 'react';
import { ModusWcDate } from '@trimble-oss/moduswebcomponents-react';

export default function ModusDateExamples() {
  const [dateValue, setDateValue] = useState('');

  const handleInputChange = (e: CustomEvent<InputEvent>) => {
    const inputEvent = e.detail;
    const input = inputEvent?.target as HTMLInputElement;
    if (input) {
      setDateValue(input.value);
    }
  };

  return (
    <>
      <h3>Date (Controlled Input)</h3>
      <div className="grid">
        <div className="grid-row">
          <ModusWcDate
            aria-label="Controlled date input"
            label="Controlled Date"
            value={dateValue}
            onInputChange={handleInputChange}
          />
          <p>Current value: <code>{dateValue || '(empty)'}</code></p>
        </div>
      </div>
    </>
  );
}
